-- Source: ldalati
CREATE TABLE IF NOT EXISTS "ldalati" (
  "SVRBOD" NUMERIC(6),
  "SABOL" VARCHAR(0),
  "SAKOR" VARCHAR(0),
  "SAPREBAC" NUMERIC(6),
  "SAOBUSTAVE" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

BEGIN TRANSACTION;
INSERT INTO "ldalati" ("SVRBOD", "SABOL", "SAKOR", "SAPREBAC", "SAOBUSTAVE", "PRENETO", "IDBR") VALUES (NULL, '', '', NULL, '', '', NULL);
COMMIT;
