-- Source: ldbol
CREATE TABLE IF NOT EXISTS "ldbol" (
  "BR" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "POL" VARCHAR(0),
  "PRVAISPL" VARCHAR(0),
  "DOD" DATE,
  "DDO" DATE,
  "DANBOL" NUMERIC(0),
  "DANNES" NUMERIC(0),
  "DANPRO" NUMERIC(0),
  "DANNEG" NUMERIC(0),
  "DANTRU" NUMERIC(0),
  "DANKRV" NUMERIC(0),
  "BRUTO" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "DOPPIO" NUMERIC(2),
  "DOPNEZ" NUMERIC(2),
  "ZAISPLAT" NUMERIC(2),
  "SVEGA" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

