-- Source: lddd0
CREATE TABLE IF NOT EXISTS "lddd0" (
  "REDNI" NUMERIC(0),
  "MESEC" VARCHAR(0),
  "NAZMES" VARCHAR(0),
  "GODINA" VARCHAR(0),
  "ARHIVA" VARCHAR(0),
  "ARHIVA2" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

