-- Source: lddunk
CREATE TABLE IF NOT EXISTS "lddunk" (
  "GRUPA" NUMERIC(0),
  "RBR" NUMERIC(0),
  "MATICNIBR" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "KATEGOR" VARCHAR(0),
  "SIFOSNOV" VARCHAR(0),
  "OSNOVICA" NUMERIC(2),
  "IZNOS" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

