-- Source: ldgod0
CREATE TABLE IF NOT EXISTS "ldgod0" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "CASUK" NUMERIC(2),
  "DINUK" NUMERIC(2),
  "POSATU" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

