-- Source: ldinv
CREATE TABLE IF NOT EXISTS "ldinv" (
  "BR" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "CASOVI" NUMERIC(0),
  "NAK2003" NUMERIC(2),
  "PROS2002" NUMERIC(2),
  "PROCUSKL" NUMERIC(2),
  "USKLADJ" NUMERIC(2),
  "NEUSKLADJ" NUMERIC(2),
  "USKLADJ2" NUMERIC(2),
  "OSTVARCAS" NUMERIC(0),
  "NETO" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "DOPZDR" NUMERIC(2),
  "SVEGA" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

