-- Source: ldinzs
CREATE TABLE IF NOT EXISTS "ldinzs" (
  "REDNI" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "BRUTO" NUMERIC(0),
  "DOPPF" NUMERIC(0),
  "DOPZF" NUMERIC(0),
  "DOPNF" NUMERIC(0),
  "DOPSOCF" NUMERIC(0),
  "DOPPFU" NUMERIC(0),
  "DOPZFU" NUMERIC(0),
  "DOPNFU" NUMERIC(0),
  "DOPPFR" NUMERIC(0),
  "DOPZFR" NUMERIC(0),
  "DOPNFR" NUMERIC(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

