-- Source: ldinv3
CREATE TABLE IF NOT EXISTS "ldinv3" (
  "TEKST1" VARCHAR(0),
  "TEKST2" VARCHAR(0),
  "TEKST3" VARCHAR(0),
  "TEKST4" VARCHAR(0),
  "TEKST5" VARCHAR(0),
  "TEKST6" VARCHAR(0),
  "TEKST7" VARCHAR(0),
  "TEKST8" VARCHAR(0),
  "TEKST9" VARCHAR(0),
  "TEKST10" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

