-- Source: ldiosi
CREATE TABLE IF NOT EXISTS "ldiosi" (
  "MESEC" NUMERIC(0),
  "NAZMES" VARCHAR(0),
  "DATDOK" DATE,
  "UKZAPOS" NUMERIC(0),
  "BROJINVAL" NUMERIC(0),
  "UKINVAL" NUMERIC(0),
  "BROJFINANS" NUMERIC(0),
  "DINFINANS" NUMERIC(0),
  "BROJINVALU" NUMERIC(0),
  "DINUGOV" NUMERIC(0),
  "BROJUGOV" VARCHAR(0),
  "DATUGOV" DATE,
  "BROJINVALP" NUMERIC(0),
  "DINPENAL" NUMERIC(0),
  "DATUPLATEP" DATE,
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

