-- Source: ldizvn
CREATE TABLE IF NOT EXISTS "ldizvn" (
  "BROJ" NUMERIC(0),
  "MESEC" NUMERIC(0),
  "MESECI" NUMERIC(0),
  "DANA" NUMERIC(0),
  "CASMES" NUMERIC(0),
  "CASUK" NUMERIC(0),
  "CASBOL" NUMERIC(0),
  "BRUTOM4" NUMERIC(2),
  "PENSOC" NUMERIC(2),
  "BOLM4" NUMERIC(2),
  "PENBOL" NUMERIC(2),
  "BRUTOLD" NUMERIC(2),
  "BRUTOBOL" NUMERIC(2),
  "BENDOP" NUMERIC(2),
  "DATUM" DATE,
  "MTR" VARCHAR(0),
  "NAZMES" VARCHAR(0),
  "BOSNZAMES" NUMERIC(2),
  "BOSNUMES" NUMERIC(2),
  "M4GRAD" VARCHAR(0),
  "REGSOC" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

