-- Source: ldizjdop
CREATE TABLE IF NOT EXISTS "ldizjdop" (
  "TEKST1" VARCHAR(0),
  "TEKST2" VARCHAR(0),
  "TEKST3" VARCHAR(0),
  "TEKST4" VARCHAR(0),
  "TEKST5" VARCHAR(0),
  "TEKST6" VARCHAR(0),
  "TEKST7" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

