-- Source: ldizrvre
CREATE TABLE IF NOT EXISTS "ldizrvre" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "FIRMA1" VARCHAR(0),
  "PROC1" NUMERIC(2),
  "FIRMA2" VARCHAR(0),
  "PROC2" NUMERIC(2),
  "FIRMA3" VARCHAR(0),
  "PROC3" NUMERIC(2),
  "FIRMA4" VARCHAR(0),
  "PROC4" NUMERIC(2),
  "FIRMA5" VARCHAR(0),
  "PROC5" NUMERIC(2),
  "MATICNIBR" VARCHAR(0),
  "POSTA" VARCHAR(0),
  "MESTO" VARCHAR(0),
  "ADRESA" VARCHAR(0),
  "TELEFON" VARCHAR(0),
  "DATDOK" DATE,
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

