-- Source: ldizvjp
CREATE TABLE IF NOT EXISTS "ldizvjp" (
  "BROJ" NUMERIC(0),
  "IME" VARCHAR(0),
  "PREZIME" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "RMESTO" VARCHAR(0),
  "SKOSPREMA" VARCHAR(0),
  "ZARADA" NUMERIC(2),
  "UVECANA" NUMERIC(2),
  "VARIJABIL" NUMERIC(2),
  "NETOLD" NUMERIC(2),
  "BRUTO" NUMERIC(2),
  "MESEC" NUMERIC(0),
  "NAZMES" VARCHAR(0),
  "ISPLATA" NUMERIC(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

