-- Source: ldkon
CREATE TABLE IF NOT EXISTS "ldkon" (
  "VRSTA" VARCHAR(0),
  "KOD" VARCHAR(0),
  "OPIS" VARCHAR(0),
  "KONTO" VARCHAR(0),
  "KONTOP" VARCHAR(0),
  "IZNOS" NUMERIC(2),
  "DATDOK" DATE,
  "BRNAL" VARCHAR(0),
  "MP" VARCHAR(0),
  "MTR" NUMERIC(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

