-- Source: ldkon00
CREATE TABLE IF NOT EXISTS "ldkon00" (
  "VRSTA" VARCHAR(0),
  "KOD" VARCHAR(0),
  "OPIS" VARCHAR(0),
  "KONTO" VARCHAR(0),
  "KONTOP" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

