-- Source: ldkred
CREATE TABLE IF NOT EXISTS "ldkred" (
  "KREDIT" NUMERIC(0),
  "BROJ" NUMERIC(0),
  "SIFRA" VARCHAR(0),
  "PARTIJA" VARCHAR(0),
  "IZNOS" NUMERIC(2),
  "KOLIKO" NUMERIC(0),
  "PRVARATA" NUMERIC(2),
  "OSTALERATE" NUMERIC(2),
  "ZADOBITAK" VARCHAR(0),
  "AKTIVRATA" NUMERIC(2),
  "AKONTRATA" NUMERIC(2),
  "OSTATAK" NUMERIC(2),
  "ODBIJENO" NUMERIC(2),
  "EVIDBROJ" VARCHAR(0),
  "MODELO" VARCHAR(0),
  "DATDOK" DATE,
  "GRUPA" NUMERIC(0),
  "ARHIVA" VARCHAR(0),
  "ARHIVA2" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

BEGIN TRANSACTION;
INSERT INTO "ldkred" ("KREDIT", "BROJ", "SIFRA", "PARTIJA", "IZNOS", "KOLIKO", "PRVARATA", "OSTALERATE", "ZADOBITAK", "AKTIVRATA", "AKONTRATA", "OSTATAK", "ODBIJENO", "EVIDBROJ", "MODELO", "DATDOK", "GRUPA", "ARHIVA", "ARHIVA2", "PRENETO", "IDBR") VALUES (NULL, NULL, '', '', NULL, NULL, NULL, 0, '', NULL, 1, 19, 04, '', '', NULL, NULL, '', '', '', NULL);
COMMIT;
