-- Source: ldkredr
CREATE TABLE IF NOT EXISTS "ldkredr" (
  "KREDIT" NUMERIC(0),
  "BROJ" NUMERIC(0),
  "SIFRA" VARCHAR(0),
  "DATDOK" DATE,
  "DUG" NUMERIC(2),
  "IZNOS" NUMERIC(2),
  "SALDO" NUMERIC(2),
  "BRNAL" VARCHAR(0),
  "DEV" VARCHAR(0),
  "DEVKURS" NUMERIC(6),
  "DEVDUG" NUMERIC(6),
  "DEVPOT" NUMERIC(6),
  "DEVSALDO" NUMERIC(6),
  "MESEC" NUMERIC(0),
  "ARHIVA" VARCHAR(0),
  "ARHIVA2" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

