-- Source: ldm4pod
CREATE TABLE IF NOT EXISTS "ldm4pod" (
  "K1" VARCHAR(0),
  "GODINA" VARCHAR(0),
  "MFROLNA" VARCHAR(0),
  "MFPOZIC" VARCHAR(0),
  "PIB" VARCHAR(0),
  "REGBROJ" VARCHAR(0),
  "DELATNOST" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

