-- Source: ldnovirz
CREATE TABLE IF NOT EXISTS "ldnovirz" (
  "REDBR" NUMERIC(0),
  "DEKLARAC" VARCHAR(0),
  "BOPBROJ" VARCHAR(0),
  "NAZMES" VARCHAR(0),
  "PIB" VARCHAR(0),
  "JMBGPODNOS" VARCHAR(0),
  "MATICNI" VARCHAR(0),
  "NAZIV" VARCHAR(0),
  "SEDISTE" VARCHAR(0),
  "TELEFON" VARCHAR(0),
  "ULICAIBR" VARCHAR(0),
  "EMAIL" VARCHAR(0),
  "POCLICA" NUMERIC(0),
  "DANLICA" NUMERIC(0),
  "IZNOS" NUMERIC(2),
  "ZIRORAC" VARCHAR(0),
  "BANKA" VARCHAR(0),
  "DATPOD" DATE,
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0),
  "DATZANADAN" DATE,
  "DATNOVOZOD" DATE
);

