-- Source: ldnovir
CREATE TABLE IF NOT EXISTS "ldnovir" (
  "REDBR" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "PREZIME" VARCHAR(0),
  "IME" VARCHAR(0),
  "DATZAPOS" DATE,
  "DATOTKAZ" DATE,
  "BROJ" NUMERIC(0),
  "OZNOLAKS" VARCHAR(0),
  "POSTA" VARCHAR(0),
  "MESTO" VARCHAR(0),
  "ADRESA" VARCHAR(0),
  "TELEFON" VARCHAR(0),
  "STAMPA" VARCHAR(0),
  "IZNOS" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

