-- Source: ldnz1
CREATE TABLE IF NOT EXISTS "ldnz1" (
  "BR" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "BRUTO" NUMERIC(2),
  "PDETE" NUMERIC(2),
  "OPOSTO" NUMERIC(2),
  "TPOSTO" NUMERIC(2),
  "SPOSTO" NUMERIC(2),
  "OSNOVP" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "ZAISPLAT" NUMERIC(2),
  "DOP" NUMERIC(2),
  "OBAVEZE" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

