-- Source: ldod1
CREATE TABLE IF NOT EXISTS "ldod1" (
  "KOD" VARCHAR(0),
  "OPIS" VARCHAR(0),
  "PORODILJE" NUMERIC(2),
  "BOLOVANJE" NUMERIC(2),
  "INVALIDI" NUMERIC(2),
  "RLINI" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

