-- Source: ldod1n
CREATE TABLE IF NOT EXISTS "ldod1n" (
  "KOD" VARCHAR(0),
  "OPIS" VARCHAR(0),
  "PORODILJE" NUMERIC(2),
  "BOLOVANJE" NUMERIC(2),
  "INVALIDI" NUMERIC(2),
  "RLINI" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

BEGIN TRANSACTION;
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', I, NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', NULL, NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 1., NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 2., NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', NULL, NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', NULL, NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., 1., NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', NULL, NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', NULL, NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., 1., 1., '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., 1., 2., '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., 1., 3., '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., 2., NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', NULL, NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', NULL, NULL, NULL, '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., 2., 1., '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., 2., 2., '', '', NULL);
INSERT INTO "ldod1n" ("KOD", "OPIS", "PORODILJE", "BOLOVANJE", "INVALIDI", "RLINI", "PRENETO", "IDBR") VALUES ('', '', 3., 2., 3., '', '', NULL);
COMMIT;
