-- Source: ldod
CREATE TABLE IF NOT EXISTS "ldod" (
  "KOD" VARCHAR(0),
  "OPIS" VARCHAR(0),
  "AOP" VARCHAR(0),
  "SK1" NUMERIC(2),
  "SK2" NUMERIC(2),
  "SK3" NUMERIC(2),
  "SK4" NUMERIC(2),
  "SK5" NUMERIC(2),
  "SK6" NUMERIC(2),
  "SK7" NUMERIC(2),
  "SK8" NUMERIC(2),
  "SK0" NUMERIC(2),
  "LINI" VARCHAR(0),
  "RLINI" VARCHAR(0),
  "PLINI" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

