-- Source: ldopnr
CREATE TABLE IF NOT EXISTS "ldopnr" (
  "BR" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "ADRESA" VARCHAR(0),
  "DATNEZAP" DATE,
  "DATUGOVOR" DATE,
  "DATPRI" DATE,
  "DATZASNIV" DATE,
  "POROLAKS" VARCHAR(0),
  "SIME_PREZ" VARCHAR(0),
  "SMATICNI" VARCHAR(0),
  "DATGUB" DATE,
  "RAZLOG" VARCHAR(0),
  "DATUPLPOR" DATE,
  "IZNOS" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

