-- Source: ldopj
CREATE TABLE IF NOT EXISTS "ldopj" (
  "KOD" VARCHAR(0),
  "OPIS" VARCHAR(0),
  "ZAPOSL" NUMERIC(0),
  "ZARADA" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "FOND" NUMERIC(2),
  "ZAISPLAT" NUMERIC(2),
  "RLINI" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

