-- Source: ldopj6p3
CREATE TABLE IF NOT EXISTS "ldopj6p3" (
  "USLUGE" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "PIO" NUMERIC(2),
  "ZDR" NUMERIC(2),
  "NETO" NUMERIC(2),
  "CNETO" NUMERIC(2),
  "UMANJENJE" NUMERIC(2),
  "PORUPL" NUMERIC(2),
  "ZUSL" VARCHAR(0),
  "ZPOREZ" VARCHAR(0),
  "ZPIO" VARCHAR(0),
  "ZZDR" VARCHAR(0),
  "MP" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

