-- Source: ldopj5
CREATE TABLE IF NOT EXISTS "ldopj5" (
  "BROJ" NUMERIC(0),
  "SIFRAPRIH" VARCHAR(0),
  "GRUPA" NUMERIC(0),
  "DATDOK" DATE,
  "BRUTO" NUMERIC(2),
  "NEOPOREZ" NUMERIC(2),
  "NETO" NUMERIC(2),
  "PR_DOH" NUMERIC(2),
  "PORDOH" NUMERIC(2),
  "CNETO" NUMERIC(2),
  "BRUTO2" NUMERIC(2),
  "UPLACPREM2" NUMERIC(2),
  "OPOREZIVO2" NUMERIC(2),
  "PR_DOH2" NUMERIC(2),
  "PORDOH2" NUMERIC(2),
  "CNETO2" NUMERIC(2),
  "MESEC" NUMERIC(0),
  "ISPLATA" NUMERIC(0),
  "NAZMES" VARCHAR(0),
  "ARHIVA" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

