-- Source: ldopj6p2
CREATE TABLE IF NOT EXISTS "ldopj6p2" (
  "GRUPAVIRM" VARCHAR(0),
  "KOD" VARCHAR(0),
  "SIF1" VARCHAR(0),
  "MODELZ" VARCHAR(0),
  "POZIVZ" VARCHAR(0),
  "NAZRACZ" VARCHAR(0),
  "ZIRORACZ" VARCHAR(0),
  "DATDOK" DATE,
  "DUG" NUMERIC(2),
  "POZIVO" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

