-- Source: ldopj1n0
CREATE TABLE IF NOT EXISTS "ldopj1n0" (
  "SIFOPIS" VARCHAR(0),
  "OPIS1" VARCHAR(0),
  "OPIS2" VARCHAR(0),
  "RADNIKA" NUMERIC(0),
  "NEOPOREZ" NUMERIC(2),
  "PRAVO" NUMERIC(2),
  "SVENEOPOR" NUMERIC(2),
  "ISPLACENO" NUMERIC(2),
  "ZAISPLATU" NUMERIC(2),
  "SVEGA" NUMERIC(2),
  "NETOOPOR" NUMERIC(2),
  "BRUTOOPOR" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "DATDOK" DATE,
  "DATISPL" DATE,
  "NAZMES" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

BEGIN TRANSACTION;
INSERT INTO "ldopj1n0" ("SIFOPIS", "OPIS1", "OPIS2", "RADNIKA", "NEOPOREZ", "PRAVO", "SVENEOPOR", "ISPLACENO", "ZAISPLATU", "SVEGA", "NETOOPOR", "BRUTOOPOR", "POREZ", "DATDOK", "DATISPL", "NAZMES", "PRENETO", "IDBR") VALUES ('', '', '', NULL, 1, na, kn, ad, a, tr, oš, ko, va, NULL, NULL, '', '', NULL);
INSERT INTO "ldopj1n0" ("SIFOPIS", "OPIS1", "OPIS2", "RADNIKA", "NEOPOREZ", "PRAVO", "SVENEOPOR", "ISPLACENO", "ZAISPLATU", "SVEGA", "NETOOPOR", "BRUTOOPOR", "POREZ", "DATDOK", "DATISPL", "NAZMES", "PRENETO", "IDBR") VALUES ('', '', '', NULL, 2, dn, ev, ni, ca, z, a, sl, už, NULL, NULL, '', '', NULL);
INSERT INTO "ldopj1n0" ("SIFOPIS", "OPIS1", "OPIS2", "RADNIKA", "NEOPOREZ", "PRAVO", "SVENEOPOR", "ISPLACENO", "ZAISPLATU", "SVEGA", "NETOOPOR", "BRUTOOPOR", "POREZ", "DATDOK", "DATISPL", "NAZMES", "PRENETO", "IDBR") VALUES ('', '', '', NULL, 3, na, kn, ad, a, tr, oš, ko, va, NULL, NULL, '', '', NULL);
INSERT INTO "ldopj1n0" ("SIFOPIS", "OPIS1", "OPIS2", "RADNIKA", "NEOPOREZ", "PRAVO", "SVENEOPOR", "ISPLACENO", "ZAISPLATU", "SVEGA", "NETOOPOR", "BRUTOOPOR", "POREZ", "DATDOK", "DATISPL", "NAZMES", "PRENETO", "IDBR") VALUES ('', '', '', NULL, 4, na, kn, ad, a, pr, ev, oz, a, NULL, NULL, '', '', NULL);
INSERT INTO "ldopj1n0" ("SIFOPIS", "OPIS1", "OPIS2", "RADNIKA", "NEOPOREZ", "PRAVO", "SVENEOPOR", "ISPLACENO", "ZAISPLATU", "SVEGA", "NETOOPOR", "BRUTOOPOR", "POREZ", "DATDOK", "DATISPL", "NAZMES", "PRENETO", "IDBR") VALUES ('', '', '', NULL, 5, so, li, da, rn, a, po, mo, ć, NULL, NULL, '', '', NULL);
INSERT INTO "ldopj1n0" ("SIFOPIS", "OPIS1", "OPIS2", "RADNIKA", "NEOPOREZ", "PRAVO", "SVENEOPOR", "ISPLACENO", "ZAISPLATU", "SVEGA", "NETOOPOR", "BRUTOOPOR", "POREZ", "DATDOK", "DATISPL", "NAZMES", "PRENETO", "IDBR") VALUES ('', '', '', NULL, 6, po, kl, on, d, ec, i, za, po, NULL, NULL, '', '', NULL);
INSERT INTO "ldopj1n0" ("SIFOPIS", "OPIS1", "OPIS2", "RADNIKA", "NEOPOREZ", "PRAVO", "SVENEOPOR", "ISPLACENO", "ZAISPLATU", "SVEGA", "NETOOPOR", "BRUTOOPOR", "POREZ", "DATDOK", "DATISPL", "NAZMES", "PRENETO", "IDBR") VALUES ('', '', '', NULL, 7, ju, bi, la, rn, a, na, gr, ad, NULL, NULL, '', '', NULL);
INSERT INTO "ldopj1n0" ("SIFOPIS", "OPIS1", "OPIS2", "RADNIKA", "NEOPOREZ", "PRAVO", "SVENEOPOR", "ISPLACENO", "ZAISPLATU", "SVEGA", "NETOOPOR", "BRUTOOPOR", "POREZ", "DATDOK", "DATISPL", "NAZMES", "PRENETO", "IDBR") VALUES ('', '', '', NULL, 8, os, ta, lo, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL);
COMMIT;
