-- Source: ldopj8
CREATE TABLE IF NOT EXISTS "ldopj8" (
  "BROJ" NUMERIC(0),
  "SIFRAPRIH" VARCHAR(0),
  "GRUPA" NUMERIC(0),
  "DATDOK" DATE,
  "NEOPOREZ" NUMERIC(2),
  "NET1" NUMERIC(2),
  "NET2" NUMERIC(2),
  "NOPOREZ" NUMERIC(2),
  "OPOREZ" NUMERIC(2),
  "N2OPOREZ" NUMERIC(2),
  "PR_NORM" NUMERIC(2),
  "NORMIRTR" NUMERIC(2),
  "N3OPOREZ" NUMERIC(2),
  "PR_DOH" NUMERIC(2),
  "PORDOH" NUMERIC(2),
  "ZAISPLATU" NUMERIC(2),
  "MESEC" NUMERIC(0),
  "ISPLATA" NUMERIC(0),
  "NAZMES" VARCHAR(0),
  "ARHIVA" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

