-- Source: ldos
CREATE TABLE IF NOT EXISTS "ldos" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "DATOD" DATE,
  "DATDO" DATE,
  "BRUTO" NUMERIC(2),
  "DOPPR" NUMERIC(2),
  "DOPZR" NUMERIC(2),
  "DOPNR" NUMERIC(2),
  "DOPPF" NUMERIC(2),
  "BENDIN" NUMERIC(2),
  "DOPZF" NUMERIC(2),
  "DOPNF" NUMERIC(2),
  "OPSTINA" VARCHAR(0),
  "MP" VARCHAR(0),
  "MESEC" NUMERIC(0),
  "NAZMES" VARCHAR(0),
  "ISPLATA" NUMERIC(0),
  "MATICNIBR" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

