-- Source: ldoz10
CREATE TABLE IF NOT EXISTS "ldoz10" (
  "BR" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "POL" VARCHAR(0),
  "PRVAISPL" VARCHAR(0),
  "DOD" DATE,
  "DDO" DATE,
  "BOLEST" NUMERIC(0),
  "POVRAD" NUMERIC(0),
  "PROFBOL" NUMERIC(0),
  "NEGA65" NUMERIC(0),
  "NEGA" NUMERIC(0),
  "IZOLAC" NUMERIC(0),
  "DAVALAC" NUMERIC(0),
  "TRUDNOCA" NUMERIC(0),
  "BRUTO" NUMERIC(2),
  "DOPR" NUMERIC(2),
  "DOPF" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "ZAISPLAT" NUMERIC(2),
  "SVEGA" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

