-- Source: ldoz09
CREATE TABLE IF NOT EXISTS "ldoz09" (
  "K1ZARADA" NUMERIC(2),
  "K1SATI" NUMERIC(2),
  "K1POSATU" NUMERIC(2),
  "K1MOGSATI" NUMERIC(2),
  "K1PROSMES" NUMERIC(2),
  "K1PZARADA" NUMERIC(2),
  "K2ZARADA" NUMERIC(2),
  "K2SATI" NUMERIC(2),
  "K2POSATU" NUMERIC(2),
  "K2MOGSATI" NUMERIC(2),
  "K2PROSMES" NUMERIC(2),
  "K2PZARADA" NUMERIC(2),
  "KOEF" NUMERIC(4),
  "MESEC1" VARCHAR(0),
  "MESEC2" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

