-- Source: ldporp12
CREATE TABLE IF NOT EXISTS "ldporp12" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "MES" NUMERIC(0),
  "MESEC" VARCHAR(0),
  "BRUTO" NUMERIC(2),
  "NETO" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

