-- Source: ldpotv2
CREATE TABLE IF NOT EXISTS "ldpotv2" (
  "TEXT1" VARCHAR(0),
  "TEXT2" VARCHAR(0),
  "TEXT3" VARCHAR(0),
  "TEXT4" VARCHAR(0),
  "TEXT5" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

BEGIN TRANSACTION;
INSERT INTO "ldpotv2" ("TEXT1", "TEXT2", "TEXT3", "TEXT4", "TEXT5", "PRENETO", "IDBR") VALUES ('', '', '', '', '', '', NULL);
COMMIT;
