-- Source: ldpotvr
CREATE TABLE IF NOT EXISTS "ldpotvr" (
  "BR" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "MESEC" VARCHAR(0),
  "BRUTO" NUMERIC(2),
  "BRUTO2" NUMERIC(2),
  "DATISPL" DATE,
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

