-- Source: ldpotv
CREATE TABLE IF NOT EXISTS "ldpotv" (
  "MESEC" NUMERIC(0),
  "PRIKAZ" VARCHAR(0),
  "LIN" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

BEGIN TRANSACTION;
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
INSERT INTO "ldpotv" ("MESEC", "PRIKAZ", "LIN", "PRENETO", "IDBR") VALUES (NULL, '', '', '', NULL);
COMMIT;
