-- Source: ldporpot
CREATE TABLE IF NOT EXISTS "ldporpot" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "MES" NUMERIC(0),
  "MESEC" VARCHAR(0),
  "RADDIN" NUMERIC(2),
  "RADKOEF" NUMERIC(4),
  "FIRDIN" NUMERIC(2),
  "FIRKOEF" NUMERIC(4),
  "MATICNIBR" VARCHAR(0),
  "LBOBROJ" VARCHAR(0),
  "ZKBROJ" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

