-- Source: ldporsta
CREATE TABLE IF NOT EXISTS "ldporsta" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "GOD" NUMERIC(0),
  "MESECI" NUMERIC(0),
  "DANA" NUMERIC(0),
  "PROCVR" NUMERIC(0),
  "ODDAT" DATE,
  "DODAT" DATE,
  "ODDATNEGA" DATE,
  "DODATNEGA" DATE,
  "DATPOS" DATE,
  "DATZAHTEV" DATE,
  "DATDOZNA" DATE,
  "ZCNAZIV" VARCHAR(0),
  "ZCMESTO" VARCHAR(0),
  "IZVODMK" VARCHAR(0),
  "IZVODMES" VARCHAR(0),
  "DETEIME" VARCHAR(0),
  "DETERODJ" DATE,
  "DETERED" VARCHAR(0),
  "NAZSUDA" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

