-- Source: ldprosz
CREATE TABLE IF NOT EXISTS "ldprosz" (
  "MESEC" NUMERIC(0),
  "VAZI" VARCHAR(0),
  "CASUK" NUMERIC(2),
  "DINUK" NUMERIC(2),
  "DINCAS" NUMERIC(2),
  "CASMES" NUMERIC(2),
  "DINEFEKT" NUMERIC(2),
  "INDEKS" NUMERIC(2),
  "RADNIKA" NUMERIC(0),
  "PUTANJA" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

