-- Source: ldprip
CREATE TABLE IF NOT EXISTS "ldprip" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "CASRAD" NUMERIC(0),
  "CASBOL" NUMERIC(0),
  "NETO" NUMERIC(2),
  "NETOBOL" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "DOPSOCR" NUMERIC(2),
  "UKUPNO" NUMERIC(2),
  "NIVO" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

