-- Source: ldprevP
CREATE TABLE IF NOT EXISTS "ldprevP" (
  "DANA" NUMERIC(1),
  "KARTA" NUMERIC(2),
  "PREVOZ" NUMERIC(2),
  "NEOPOREZ" NUMERIC(2),
  "DATUM" DATE,
  "MESEC" NUMERIC(0),
  "NAZMES" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

