-- Source: ldprev00
CREATE TABLE IF NOT EXISTS "ldprev00" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "DANA" NUMERIC(1),
  "KARTA" NUMERIC(2),
  "PREVOZ" NUMERIC(2),
  "NEOPOREZ" NUMERIC(2),
  "OPOREZ" NUMERIC(2),
  "STOPA" NUMERIC(2),
  "POREZ" NUMERIC(2),
  "UKUPPREV" NUMERIC(2),
  "DATUM" DATE,
  "GRUPA" NUMERIC(0),
  "MESEC" NUMERIC(0),
  "ISPLATA" NUMERIC(0),
  "VRSTA" VARCHAR(0),
  "NAZMES" VARCHAR(0),
  "SIFRAPRIH" VARCHAR(0),
  "ARHIVA" VARCHAR(0),
  "ARHIVA2" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

