-- Source: ldradvr
CREATE TABLE IF NOT EXISTS "ldradvr" (
  "BROJ" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "DATPOC" DATE,
  "VREMEPOC" VARCHAR(0),
  "DATKRAJ" DATE,
  "VREMEKRAJ" VARCHAR(0),
  "SATI" NUMERIC(0),
  "MINUTI" NUMERIC(0),
  "SEKUNDI" NUMERIC(0),
  "RADIO" NUMERIC(8),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

