-- Source: ldradcl
CREATE TABLE IF NOT EXISTS "ldradcl" (
  "CBROJ" NUMERIC(0),
  "BROJ" NUMERIC(0),
  "CIME_PREZ" VARCHAR(0),
  "CMATICNI" VARCHAR(0),
  "CLBOBROJ" VARCHAR(0),
  "CADRESA" VARCHAR(0),
  "CSRODSTVO" VARCHAR(0),
  "CNAPOMENA" VARCHAR(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNI" VARCHAR(0),
  "LBOBROJ" VARCHAR(0),
  "ADRESA" VARCHAR(0),
  "NAPOMENA" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

