-- Source: ldsamod
CREATE TABLE IF NOT EXISTS "ldsamod" (
  "SAMSIF" NUMERIC(0),
  "SAMONAZ" VARCHAR(0),
  "SAMOPROC" NUMERIC(4),
  "ZIRORAC" VARCHAR(0),
  "SAMODOP" NUMERIC(2),
  "SAM1" NUMERIC(2),
  "SAM2" NUMERIC(2),
  "SAM3" NUMERIC(2),
  "SAM4" NUMERIC(2),
  "MESEC" NUMERIC(0),
  "ISPLATA" NUMERIC(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

BEGIN TRANSACTION;
INSERT INTO "ldsamod" ("SAMSIF", "SAMONAZ", "SAMOPROC", "ZIRORAC", "SAMODOP", "SAM1", "SAM2", "SAM3", "SAM4", "MESEC", "ISPLATA", "PRENETO", "IDBR") VALUES (NULL, '', 1, '', 1, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL);
COMMIT;
