-- Source: ldtop
CREATE TABLE IF NOT EXISTS "ldtop" (
  "RESTORAN" NUMERIC(2),
  "KOEFB" NUMERIC(6),
  "RBRUTO" NUMERIC(2),
  "CTOP" NUMERIC(4),
  "TOPLI" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

