-- Source: ldvirm
CREATE TABLE IF NOT EXISTS "ldvirm" (
  "STAMPA" VARCHAR(0),
  "VRSTA" VARCHAR(0),
  "ZIRORAC" VARCHAR(0),
  "MODELO" VARCHAR(0),
  "POZIVO" VARCHAR(0),
  "DATDOK" DATE,
  "DUG" NUMERIC(2),
  "SIF1" VARCHAR(0),
  "MODELZ" VARCHAR(0),
  "POZIVZ" VARCHAR(0),
  "NAZRAC" VARCHAR(0),
  "SVRHA" VARCHAR(0),
  "RAZ" VARCHAR(0),
  "NAZRACZ" VARCHAR(0),
  "ZIRORACZ" VARCHAR(0),
  "UKUPNO" NUMERIC(2),
  "DATVAL" DATE,
  "VALUTA" VARCHAR(0),
  "PLAC" NUMERIC(2),
  "MESTO" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

