-- Source: ldz1
CREATE TABLE IF NOT EXISTS "ldz1" (
  "BR" VARCHAR(0),
  "OPIS" VARCHAR(0),
  "IZNOS" NUMERIC(2),
  "PODATAK" VARCHAR(0),
  "RLINI" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

