-- Source: ldzo22
CREATE TABLE IF NOT EXISTS "ldzo22" (
  "BR" VARCHAR(0),
  "PREZIME" VARCHAR(0),
  "IME" VARCHAR(0),
  "RODITELJ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "DOD" DATE,
  "DDO" DATE,
  "CASOVI" NUMERIC(2),
  "IZNOS" NUMERIC(2),
  "NECASOVI" NUMERIC(2),
  "RADNOVRE" VARCHAR(0),
  "RADNOVRE2" VARCHAR(0),
  "NAPOMENA1" VARCHAR(0),
  "NAPOMENA2" VARCHAR(0),
  "NAPOMENA3" VARCHAR(0),
  "NAPOMENA4" VARCHAR(0),
  "DATUM" DATE,
  "IZNOSCAS" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

