-- Source: ldzo24
CREATE TABLE IF NOT EXISTS "ldzo24" (
  "MESEC2" VARCHAR(0),
  "MESEC3" VARCHAR(0),
  "UKIZN12" NUMERIC(2),
  "UKIZN13" NUMERIC(2),
  "UKCAS22" NUMERIC(2),
  "UKCAS23" NUMERIC(2),
  "PROS32" NUMERIC(2),
  "PROS33" NUMERIC(2),
  "PORAST" NUMERIC(2),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

