-- Source: ldzsd
CREATE TABLE IF NOT EXISTS "ldzsd" (
  "REDNI" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "DATZAPOS" DATE,
  "BRUTO" NUMERIC(0),
  "DOPPF" NUMERIC(0),
  "DOPPFR" NUMERIC(0),
  "DOPPUK" NUMERIC(0),
  "DATOTKAZ" DATE,
  "DOPDUG" NUMERIC(0),
  "BROJZAP0" NUMERIC(0),
  "BROJZAP1" NUMERIC(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

