-- Source: ldzsp
CREATE TABLE IF NOT EXISTS "ldzsp" (
  "REDNI" NUMERIC(0),
  "IME_PREZ" VARCHAR(0),
  "MATICNIBR" VARCHAR(0),
  "PORUMANJ" NUMERIC(4),
  "DATZAPOS" DATE,
  "BRUTO" NUMERIC(0),
  "PORDOH" NUMERIC(2),
  "POREZU" NUMERIC(2),
  "POREZUPL" NUMERIC(2),
  "POREZSUB" NUMERIC(2),
  "DATOTKAZ" DATE,
  "PORDUG" NUMERIC(0),
  "BROJZAP0" NUMERIC(0),
  "BROJZAP1" NUMERIC(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

