-- Source: ldzzo02
CREATE TABLE IF NOT EXISTS "ldzzo02" (
  "TEXT1" VARCHAR(0),
  "TEXT2" VARCHAR(0),
  "TEXT3" VARCHAR(0),
  "TEXT4" VARCHAR(0),
  "TEXT5" VARCHAR(0),
  "PRENETO" VARCHAR(0),
  "IDBR" NUMERIC(0)
);

